modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "https://github.com/Seniorendi/AdvancedPeripherals/issues"
logoFile = "pack.png"
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Advanced Peripherals"
displayURL = "https://docs.intelligence-modding.de/"
authors = "Srendi"
description = '''
Advanced Peripherals provides multiple extensions for ComputerCraft in form of Peripherals, Pocket Upgrades, Turtles or new gear.
It also integrates with multiple third party mods.
'''
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "computercraft"
type = "required"
versionRange = "[${cc_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "curios"
type = "optional"
versionRange = "[${curios_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "ae2"
type = "optional"
versionRange = "[${appliedenergistics_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "refinedstorage"
type = "optional"
versionRange = "[${refinedstorage_version},)"
ordnering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "minecolonies"
type = "optional"
versionRange = "[${minecolonies_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "patchouli"
type = "optional"
versionRange = "[${patchouli_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "create"
type = "optional"
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "botania"
type = "optional"
versionRange = "[${botania_version},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "mekanism"
type = "optional"
versionRange = "[${mekanism_version},)"
ordering = "NONE"
side = "BOTH"